jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/r-wasm/webr:main
    steps:
    - uses: actions/checkout@v3
    - name: Build wasm packages
      uses: r-wasm/actions/build-wasm-packages@v1
      with:
        upload-image: true
        upload-repo: false
        strip: c("demo", "doc", "examples", "help")
